<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-02 23:13
=======
# Generated by Django 5.2.7 on 2025-11-02 21:15
>>>>>>> 4f37f173aa912a96ed7725df85ced0136f51c3c3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_search', '0003_alter_recipe_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='recipe_search.recipe')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reapers_profile.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'recipe')},
            },
        ),
=======
                ('liked_recipes', models.ManyToManyField(blank=True, related_name='liked_by', to='recipe_search.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
>>>>>>> 4f37f173aa912a96ed7725df85ced0136f51c3c3
    ]
