# Generated by Django 5.2.7 on 2025-10-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
