# Generated by Django 5.2.7 on 2025-11-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_search', '0002_rename_instructions_recipe_recipe_delete_ingredient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('recipe',)},
        ),
    ]
